config/routes.rb
Rails.application.routes.draw do
  get 'about_us/index', to: 'about_us#index'
  get 'center/index'
  devise_for :users
  root to: "pages#home"
  resources :hospitals
  resources :donors
  resources :centers do
    resources :reviews
  end
  resources :appointments do
    member do
      get :cancel
      get :approve
      get :deny
    end
  end
  resources :schedules
  resources :days
  get 'about_us', to: 'about_us#index'
end

app/models/donor.rb
class Donor < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :appointments
  validates :user_id, uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_donor_category
  before_action :set_donor, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.hospital?
      @donors = Donor.all
    else
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end

  def show
    @donor = current_user.donor

    authorize @donor

    if @donor.nil?
      redirect_to new_donor_path, alert: "Please create a donor profile"
      return
    end

    @appointments = @donor.appointments
  end

  def new
    @donor = Donor.new
    authorize @donor
  end

  def create
    @donor = Donor.new(donor_params)

    authorize @donor

    @donor.user = current_user
    if @donor.save
      redirect_to root_path, notice: 'Donor was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def edit
    authorize @donor
  end

  def update
    authorize @donor
    if @donor.update(donor_params)
      redirect_to donor_path(@donor), notice: 'Donor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @donor.destroy
    redirect_to donors_url, notice: 'Donor was successfully destroyed.'
  end

  private

  def check_donor_category
    redirect_to root_path, alert: "You are not authorized to access this page" unless current_user.donor?
  end

  def set_donor
    @donor = Donor.find(params[:id])
  end

  def donor_params
    params.require(:donor).permit(:address, :blood_type, :birthdate, :first_name, :last_name, :national_id)
  end
end

app/views/donors/_form_edit.html.erb
<div class="container" style="padding: 50px;">
  <%= form_with(model: @donor, url: donor_path(@donor), method: "patch") do |form| %>

    <%= form.label :first_name, "First Name" %>
    <%= form.text_field :first_name, class: "form-control" %>

    <%= form.label :last_name, "Last Name" %>
    <%= form.text_field :last_name, class: "form-control" %>

    <%= form.label :address, "Address" %>
    <%= form.text_area :address, class: "form-control" %>

    <%= form.label :blood_type, "Blood Type" %>
    <%= form.text_field :blood_type, class: "form-control" %>

    <%= form.label :birthdate, "Birthdate" %>
    <%= form.date_field :birthdate, class: "form-control" %>

    <%= form.label :national_id, "National ID" %>
    <%= form.text_field :national_id, class: "form-control" %>

    <div class="donor-profile-edit-actions">
      <%= form.button :submit, class: "btn-link" %>
    </div>
  <% end %>
</div>

app/views/donors/_form_new.html.erb
<div class="container" style="padding: 50px;">
  <%= form_with(model: @donor, url: donors_path, method: "post") do |form| %>

    <%= form.label :first_name, "First Name" %>
    <%= form.text_field :first_name, class: "form-control" %>

    <%= form.label :last_name, "Last Name" %>
    <%= form.text_field :last_name, class: "form-control" %>

    <%= form.label :address, "Address" %>
    <%= form.text_area :address, class: "form-control" %>

    <%= form.label :blood_type, "Blood Type" %>
    <%= form.text_field :blood_type, class: "form-control" %>

    <%= form.label :birthdate, "Birthdate" %>
    <%= form.date_field :birthdate, class: "form-control" %>

    <%= form.label :national_id, "National ID" %>
    <%= form.text_field :national_id, class: "form-control" %>

    <div class="actions">
      <%= form.button :submit, class: "btn-link" %>
    </div>
  <% end %>
</div>

app/views/donors/edit.html.erb
<div class="donor-new">
  <h1>Edit Donor</h1>
</div>
<%= render 'form_edit', donor: @donor %>

app/views/donors/index.html.erb
<h1>Donors</h1>
<ul>
  <% @donors.each do |donor| %>
    <% if donor %>
      <li><%= link_to "#{donor.first_name} #{donor.last_name}", donor %></li>
    <% else %>
      <li>No donor record found.</li>
    <% end %>
  <% end %>
</ul>

<%= link_to "Create New Profile", new_donor_path %>

app/views/donors/new.html.erb
<div class="donor-new">
    <h1>New Donor</h1>
</div>
<%= render 'form_new', donor: @donor %>

app/views/donors/show.html.erb
<div class="donor-index">
  <div class="donor-profile">
    <div><h3 class="my-profile-text">Profile Page</h3></div>
    <div class="donor_profile_links">
      <div><%= link_to 'Back', root_path, class: "profile-link-back" %></div>
      <div><%= link_to 'New Appointment', new_appointment_path, class: 'new-appointment-btn-show' %></div>
    </div>
  </div>

  <div class="profile_content">
    <div class="profile_details">
      <div class="profile-header">My Profile</div>
      <div class="my_profile_text">
        <div><p><strong>First Name:</strong> <%= content_tag :span, @donor.first_name, class: 'profile-details-text-black' %></p></div>
        <div><p><strong>Last Name:</strong> <%= content_tag :span, @donor.last_name, class: 'profile-details-text-black' %></p></div>
        <div><p><strong>Address:</strong> <%= content_tag :span, @donor.address, class: 'profile-details-text-black' %></p></div>
        <div><p><strong>Blood Type:</strong> <%= content_tag :span, @donor.blood_type, class: 'profile-details-text-black' %></p></div>
        <div><p><strong>Birthdate:</strong> <%= content_tag :span, @donor.birthdate, class: 'profile-details-text-black' %></p></div>
        <div><p><strong>National ID:</strong> <%= content_tag :span, @donor.national_id, class: 'profile-details-text-black' %></p></div>
        <div class="edit-donor-profile">
          <div><%= link_to 'Edit', edit_donor_path(@donor), class: "profile-link-edit" %></div>
          <div><%= link_to "Delete",
                          donor_path(@donor),
                          data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                          class: "profile-link-delete" %></div>
        </div>
      </div>
    </div>

    <div class="show_appointments">
      <div class="my-profile-div">
        <div>My appointments</div>
      </div>
      <div>
        <div class="appointment_grid">
          <% if @appointments.any? %>
            <% @appointments.each do |appointment| %>
              <div class="profile-appointment">
                <div class="detail">
                  <strong>Date:</strong>
                  <%= appointment.appointment_date %>
                </div>
                <div class="detail">
                  <strong>Time:</strong>
                  <%= appointment.appointment_time.strftime("%H:%M") %>
                </div>
                <div class="detail">
                  <strong>Center Name:</strong>
                  <%= appointment.center.name %>
                </div>
                <div class="detail">
                  <strong>Center Address:</strong>
                  <%= appointment.center.address %>
                </div>
                <div class="detail">
                  <strong>Donor:</strong>
                  <%= appointment.donor.full_name %>
                </div>
                <div class="detail">
                  <strong>Status:</strong>
                  <span class="status-<%= appointment.status %>">
                    <%= appointment.status.presence || 'N/A' %>
                  </span>
                </div>

                <div class="detail">
                  <%= link_to 'Show', appointment, class: 'profile-appointment-show' %>
                  <% if appointment.status != "canceled" %>
                    <%= link_to 'Cancel', cancel_appointment_path(appointment), method: :post, data: { turbo_confirm: 'Are you sure you want to cancel this appointment?' }, class: 'profile-appointment-show' %>
                  <% end %>
                </div>
              </div>

            <% end %>
            <% else %>
                No appointments
            <% end %>
      </div>


      </div>

    </div>
  </div>
</div>