config/routes.rb
Rails.application.routes.draw do
  get 'about_us/index', to: 'about_us#index'
  get 'center/index'
  devise_for :users
  root to: "pages#home"
  resources :hospitals
  resources :donors
  resources :centers do
    resources :reviews
  end
  resources :appointments do
    member do
      get :cancel
      get :approve
      get :deny
    end
  end
  resources :schedules
  resources :days
  get 'about_us', to: 'about_us#index'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div>© GIVE YOUR BLOOD</div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbarlight navbar-lewagon">
  <div class="container-fluid">
    <div class="navbar-left">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home",root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
            <% if current_user && current_user.hospital? %>
              <% hospital_center = current_user.center %>
              <% if hospital_center %>
                <%= link_to "My Center", center_path(hospital_center), class: "nav-link"%>
              <% end %>
            <% else %>
              <%= link_to "Locations", centers_path, class: "nav-link"%>
            <% end %>
          </li>
      </ul>
    </div>

    <div class="navbar-middle">
      <%= link_to root_path, class: "navbar-brand logo-txt" do %>
        GIVE YOUR BLOOD
      <% end %>
    </div>

    <div class="navbar-right">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to  "About us", about_us_path, class: "nav-link"%>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= 'Menu' %>
            </a>

           <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <% if current_user.category == "donor" %>
                <% if current_user && current_user.donor %>
                  <%= link_to "Donor Profile", donor_path(current_user.donor), class: "dropdown-item" %>
                <% else %>
                  <%= link_to "Create Donor Profile", new_donor_path, class: "dropdown-item" %>
                <% end %>
              <% else %>
                <% if current_user && current_user.hospital %>
                  <%= link_to "Hospital Profile", hospital_path(current_user.hospital), class: "dropdown-item" %>
                <% else %>
                  <%= link_to "Create Hospital Profile", new_hospital_path, class: "dropdown-item" %>
                <% end %>
              <% end %>

              <%= link_to "Log out", destroy_user_session_path,  class: "dropdown-item", data: { turbo_method: :delete } %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>