config/routes.rb
Rails.application.routes.draw do
  get 'about_us/index', to: 'about_us#index'
  get 'center/index'
  devise_for :users
  root to: "pages#home"
  resources :hospitals
  resources :donors
  resources :centers do
    resources :reviews
  end
  resources :appointments do
    member do
      get :cancel
      get :approve
      get :deny
    end
  end
  resources :schedules
  resources :days
  get 'about_us', to: 'about_us#index'
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  belongs_to :user
  has_many :centers
  has_many :donors, through: :centers
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_hospital_category
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  def index
    @hospital = current_user.hospital
  end

  def show
    authorize @hospital
    @appointments = Appointment.where(center_id: @hospital.centers)
    @approved_appointments = Appointment.where(center_id: @hospital.centers, status: "approved").where('appointment_date >= ?', Time.zone.now.beginning_of_day)
  end

  def new
    @hospital = Hospital.new
    authorize @hospital
  end

  def create
    @hospital = Hospital.new(hospital_params) 
    authorize @hospital
    @hospital.user = current_user
    if @hospital.save
      redirect_to @hospital, notice: 'Hospital was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize @hospital
  end

  def update
    if @hospital.update(hospital_params)
      authorize @hospital
      redirect_to @hospital, notice: 'Hospital was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @hospital.destroy
    authorize @hospital
    @hospital.destroy
    redirect_to root_path, notice: 'Hospital was successfully destroyed.'
  end

  private

  def check_hospital_category
    redirect_to root_path, alert: "You are not authorized to access this page" unless current_user.hospital?
  end

  def set_hospital
    @hospital = Hospital.find(params[:id])
  end

  def hospital_params
    params.require(:hospital).permit(:hospital_name)
  end
end

app/views/hospitals/_form_edit.html.erb
<div class="container" style="padding: 50px; margin-top: 60px;">
  <%= simple_form_for(@hospital, url: hospital_path(@hospital), method: "patch") do |form| %>
    <% if @hospital.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>
        <ul>
        <% @hospital.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.input :hospital_name, label: "Hospital Name", input_html: { class: "form-control" } %>

    <div class="actions">
      <%= form.button :submit, "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/hospitals/_form_new.html.erb
<div class="container" style="padding: 50px; margin-top: 60px;">
  <%= simple_form_for(@hospital, url: hospitals_path(@hospital), method: "post") do |form| %>
    <% if @hospital.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>
        <ul>
        <% @hospital.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.input :hospital_name, label: "Hospital Name", input_html: { class: "form-control" } %>

    <div class="actions">
      <%= form.button :submit, "Create Hospital", class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/hospitals/edit.html.erb
<h1>Edit Hospital</h1>
<%= render 'form_edit', hospital: @hospital %>

app/views/hospitals/index.html.erb
<h1>Hospitals</h1>
<ul>
  <% @hospitals.each do |hospital| %>
    <li><%= link_to hospital.hospital_name, hospital %></li>
  <% end %>
</ul>

app/views/hospitals/new.html.erb
<div class="hospital-new">
  <h1>New Hospital</h1>
</div>

<%= render 'form_new', hospital: @hospital %>

app/views/hospitals/show.html.erb
<% pending_appointments = @appointments.select {|appointment| appointment.status == "pending"} %>

<div class="donor-index">
  <div class="donor-profile">
    <div>
      <h3 class="my-profile-text">Profile Page</h3>
    </div>
    <div>
      <a href="<%= new_center_path %>" class="hospital-profile-new-center">New Center</a>
    </div>
  </div>

  <div class="profile_contents">
    <div class="profile_details">
      <div class="profile-header">My Profile</div>
      <div class="my_profile_text">
        <div>
          <p><strong>Name:</strong> <%= content_tag :span, @hospital.hospital_name, class: 'profile-details-text-black' %></p>
        </div>
        <div class="edit-donor-profile">
          <div><%= link_to 'Edit', edit_hospital_path(@hospital), class: "profile-link-edit" %></div>
          <div><%= link_to "Delete",
                          hospital_path(@hospital),
                          data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                          class: "profile-link-delete" %></div>
        </div>
      </div>
    </div>

    <div class="show_appointments">
      <div class="my-profile-div">
        <h5>All your requested appointments</h5>

      </div>
      <div class="appointment_grid">
        <% if pending_appointments.any? %>
          <% pending_appointments.each do |appointment| %>
            <div class="profile-appointment">
              <div class="detail">
                <strong>Date:</strong>
                <%= appointment.appointment_date %>
              </div>
              <div class="detail">
                <strong>Time:</strong>
                <%= appointment.appointment_time.strftime("%H:%M") %>
              </div>
              <div class="detail">
                <strong>Center Name:</strong>
                <%= appointment.center.name %>
              </div>
              <div class="detail">
                <strong>Center Address:</strong>
                <%= appointment.center.address %>
              </div>
              <div class="detail">
                <strong>Donor:</strong>
                <%= appointment.donor.full_name %>
              </div>
              <div class="detail">
                <strong>Status:</strong>
                <span class="status-<%= appointment.status %>">
                  <%= appointment.status.presence || 'N/A' %>
                </span>
              </div>

              <div class="detail">
                  <%= link_to 'Approve', approve_appointment_path(appointment), method: :post, data: { turbo_confirm: 'Are you sure you want to aprove this appointment?' }, class: 'profile-appointment-show' %>
                  <%= link_to 'Deny', deny_appointment_path(appointment), method: :post, data: { turbo_confirm: 'Are you sure you want to deny this appointment?' }, class: 'profile-appointment-show' %>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>No appointments</p>
        <% end %>
      </div>
    </div>


  </div>
  <div class="d-flex justify-content-end">
      <div class="existing-appointment">
        <div class="my-profile-div">
          <h5>Your upcomming appointments</h5>
        </div>
        <div class="appointment_grid">
          <% current_date = Date.current %>

          <% if @approved_appointments.any? %>
            <% @approved_appointments.each do |appointment| %>
              <div class="profile-appointment">
                <div class="detail">
                  <strong>Date:</strong>
                  <%= appointment.appointment_date %>
                </div>
                <div class="detail">
                  <strong>Time:</strong>
                <%= appointment.appointment_time.strftime("%H:%M") %>
                </div>
                <div class="detail">
                  <strong>Center Name:</strong>
                  <%= appointment.center.name %>
                </div>
                <div class="detail">
                  <strong>Center Address:</strong>
                  <%= appointment.center.address %>
                </div>
                <div class="detail">
                  <strong>Donor:</strong>
                  <%= appointment.donor.full_name %>
                </div>
                <div class="detail">
                  <strong>Status:</strong>
                  <span class="status-<%= appointment.status %>">
                    <%= appointment.status.presence || 'N/A' %>
                  </span>
                </div>
                <div class="detail">
                  <%= link_to 'Show', appointment, class: 'profile-appointment-show' %>
                  <% if appointment.status != "canceled" %>
                    <%= link_to 'Cancel', cancel_appointment_path(appointment), method: :post, data: { turbo_confirm: 'Are you sure you want to cancel this appointment?' }, class: 'profile-appointment-show' %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% else %>
            No appointments for today
          <% end %>
        </div>
      </div>
    </div>
</div>