config/routes.rb
Rails.application.routes.draw do
  get 'about_us/index', to: 'about_us#index'
  get 'center/index'
  devise_for :users
  root to: "pages#home"
  resources :hospitals
  resources :donors
  resources :centers do
    resources :reviews
  end
  resources :appointments do
    member do
      get :cancel
      get :approve
      get :deny
    end
  end
  resources :schedules
  resources :days
  get 'about_us', to: 'about_us#index'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_center
  before_action :set_review, only: [:show, :edit]

  def index
    @reviews = policy_scope(@center.reviews)
  end

  def show
  end

  def new
    @review = @center.reviews.new
    authorize @review
  end

  def create
    @review = @center.reviews.new(review_params)
    @review.donor = current_user.donor
    authorize @review
    if @review.save!
      redirect_to center_path(@center), notice: 'Review was successfully created.'
    else
      render :show
    end
  end

  private

  def set_center
    @center = Center.find(params[:center_id])
  end

  def set_review
    @review = @center.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :review_content).merge(donor_id: current_user.id)
  end
end

app/views/reviews/edit.html.erb
<%= form_with(model: [ @center, review ], local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, step: 0.1, min: 1, max: 5 %>
  </div>

  <div class="field">
    <%= form.label :review_content %>
    <%= form.text_area :review_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', centers_path %>

app/views/reviews/index.html.erb
<h1>Reviews for <%= @center.name %></h1>

<% @reviews.each do |review| %>
  <div class="review">
    <h3>Rating: <%= review.rating %></h3>
    <p><%= review.review_content %></p>
  </div>
<% end %>

<%= link_to "Add Review", new_center_review_path(@center) %>
<%= link_to 'Back', centers_path %>

app/views/reviews/new.html.erb
<h1>New Review for <%= @center.name %></h1>

<%= form_with(model: [@center, @review], local: true) do |form| %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, step: 0.1, min: 1, max: 5 %>
  </div>

  <div class="field">
    <%= form.label :review_content %>
    <%= form.text_area :review_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', centers_path %>

app/views/reviews/show.html.erb
<h1>Review for <%= @center.name %></h1>

<div class="review">
  <h3>Rating: <%= @review.rating %></h3>
  <p><%= @review.review_content %></p>
</div>

<%= link_to 'Edit Review', edit_center_review_path(@center, @review) %>
<%= link_to 'Delete Review', center_review_path(@center, @review), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', center_reviews_path(@center) %>